### ISSUE TITLE
bug#2

### ISSUE THREAD

**Issue by trololol42** [kli512/bombparty-assist#2]
With the .exe : 

Loading en dictionary...
100% (273154 of 273154) |########################################################| Elapsed Time: 0:00:06 Time:  0:00:06
Loading fr dictionary...
100% (335715 of 335715) |########################################################| Elapsed Time: 0:00:11 Time:  0:00:11

DevTools listening on ws://127.0.0.1:63213/devtools/browser/f8492512-be3b-4714-87d7-83090b8b3932

DevTools listening on ws://127.0.0.1:58264/devtools/browser/b8f70932-f60f-4ba1-ad9a-929813e5608b

DevTools listening on ws://127.0.0.1:58279/devtools/browser/9e2753a6-a021-44d3-8343-24bd322400ab

DevTools listening on ws://127.0.0.1:54921/devtools/browser/0f4437aa-888c-49fd-b781-211f07f53c72
[21744:22828:0805/190414.169:ERROR:device_event_log_impl.cc(214)] [19:04:14.169] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
'Language Français not supported'
Traceback (most recent call last):
  File "jklm_bombparty.py", line 117, in <module>
  File "jklm_bombparty.py", line 113, in main
NameError: name 'exit' is not defined
[11520] Failed to execute script jklm_bombparty

**Comment by kli512** [comment]
Use language keyword French

**Comment by trololol42** [comment]
The problem is I can't choose between French and English
